name: PSMI tests

run-name: ${{ github.actor }} is running CI pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  Unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.11]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ "${{ matrix.python-version }}" == "3.8" ]]; then
            pip install -r .github/py38-requirements.txt
          elif [[ "${{ matrix.python-version }}" == "3.11" ]]; then
            pip install -r .github/py311-requirements.txt
          fi
      - name: Show installed dependencies
        run: pip freeze
      - name: Run unit tests
        run: PYTHONPATH=. python -m pytest
